# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c1eedfcabc6d2aaa6d68625b4039916e7bbe3343f288510ae236e33f1d1693e4837ff0219d80ada148e69c96579d23e7d2de18a4564d082dd97a468f2b9034e9

test:
  secret_key_base: cfc39018a0d7ede760290cdef475cb64cf0e57ecaed8514b920ef7c7dc30c64034cdb16941c1d1d3b933b7172d93cc9cf58db894baca5158962d49470904f37d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
